package sistemapdv.janelas;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import sistemapdv.modelos.ItemVenda;
import sistemapdv.modelos.ModeloTabelaRegistroVenda;
import sistemapdv.modelos.OperacaoCadastro;
import sistemapdv.modelos.Venda;

public class JanelaRegistroVendaDlg extends javax.swing.JDialog {

    private OperacaoCadastro operacaoCadastroVenda;
    private boolean confirmado;
    private ItemVenda itemVenda;
    private static int proximoCodigoChamada = 1;
    public static double itemValorTotal = 0;
    public static double totalVenda = 0;
    private Venda venda;
    private LocalDate data;
    private LocalTime hora;
    private String dataFormatada;
    private String horaFormatada;
    
    ControladorProdutoDlg quadroProduto;
    
    private ModeloTabelaRegistroVenda modeloRegistroVenda;

    private JanelaRegistroVendaDlg(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void initTabela() {
        modeloRegistroVenda = new ModeloTabelaRegistroVenda();
        tabRegistroVenda.setModel(modeloRegistroVenda);
    }
    
    
    @SuppressWarnings("unchecked")
    public JanelaRegistroVendaDlg(java.awt.Frame parent, OperacaoCadastro operacaoCadastroVenda, Venda venda) {
        super(parent, true);
        confirmado = false;
        this.operacaoCadastroVenda = operacaoCadastroVenda;
        this.itemVenda = new ItemVenda();
        this.venda = venda;
        DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        data = LocalDate.now();
        dataFormatada = data.format(formatoData);
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");
        hora = LocalTime.now();
        horaFormatada = hora.format(formatoHora);
        
        initComponents();

        if (operacaoCadastroVenda == OperacaoCadastro.alterar
                || operacaoCadastroVenda == OperacaoCadastro.consultar) {
            edNumeroItem.setText(Integer.toString(itemVenda.getNumeroItem()));
            edCodigo.setText(Integer.toString(itemVenda.getCodigoProduto()));
            edQuantidade.setText(Integer.toString(itemVenda.getQuantidadeVendida()));
            edPreco.setText(Double.toString(itemVenda.getPrecoUnitario()));
            edDescricao.setText(itemVenda.getDescricaoProduto());
            edTotalVenda.setText(Double.toString(venda.getValorTotal()));
            edData.setText(venda.getData());
            edHora.setText(horaFormatada);
           
            
        } else {
            edNumeroItem.setText(Integer.toString(proximoCodigoChamada));
            edTotalVenda.setText(Double.toString(totalVenda));
            totalVenda += itemValorTotal;
            edData.setText(dataFormatada);
            edHora.setText(horaFormatada);
            totalVenda = 0;
            edCodigo.setText(Integer.toString(0));
            edDescricao.setText("");
            edPreco.setText(Double.toString(0));
            edQuantidade.setText(Integer.toString(0));
        }
        initTabela();  
    }

    
    public boolean operacaoConfirmada() {
        return confirmado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddProduto = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnFinalizarVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbPagamento = new javax.swing.JComboBox<>();
        edTotalVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSelecionarProduto = new javax.swing.JButton();
        edDescricao = new javax.swing.JTextField();
        edPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edNumeroItem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabRegistroVenda = new javax.swing.JTable();
        edData = new javax.swing.JTextField();
        edHora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAddProduto.setText("Adicionar");
        btnAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutoActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnFinalizarVenda.setText("Finalizar Venda");
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Forma de Pagamento:");

        cbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIX", "CARTÃO DE CRÉDITO", "CARTÃO DE DÉBITO", "DINHEIRO", "BITCOIN", "DOGECOIN", "OUTROS" }));
        cbPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPagamentoActionPerformed(evt);
            }
        });

        edTotalVenda.setEditable(false);
        edTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edTotalVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Total:");

        edQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edQuantidadeFocusGained(evt);
            }
        });

        jLabel3.setText("Produto:");

        btnSelecionarProduto.setText("Seleicionar Produto");
        btnSelecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarProdutoActionPerformed(evt);
            }
        });

        edDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edDescricaoFocusGained(evt);
            }
        });
        edDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edDescricaoActionPerformed(evt);
            }
        });

        edPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edPrecoFocusGained(evt);
            }
        });
        edPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edPrecoActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade");

        jLabel6.setText("Descrição:");

        jLabel7.setText("Preço");

        edCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edCodigoFocusGained(evt);
            }
        });

        jLabel4.setText("Cod. Produto:");

        edNumeroItem.setEditable(false);
        edNumeroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNumeroItemActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero do Item:");

        tabRegistroVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabRegistroVenda);

        edData.setEditable(false);
        edData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edDataActionPerformed(evt);
            }
        });

        edHora.setEditable(false);

        jLabel9.setText("Data:");

        jLabel10.setText("Hora:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSelecionarProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edNumeroItem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(edCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(edPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(edQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20)
                        .addComponent(edData, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edHora, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 159, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnFinalizarVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSair)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(edTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(btnSelecionarProduto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edNumeroItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddProduto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(edPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(edHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnFinalizarVenda))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarProdutoActionPerformed
        quadroProduto = new ControladorProdutoDlg(null, true);
        quadroProduto.setLocationRelativeTo(null);
        quadroProduto.setVisible(true);

        String produtoSelecionado = quadroProduto.getProdutoSelecionado();
        double precoProdutoSelecionado = quadroProduto.getPrecoProdutoSelecionado();
        int codigoProdutoSelecionado = quadroProduto.getCodigoProdutoSelecionado();

        edDescricao.setText(produtoSelecionado);
        edPreco.setText(Double.toString(precoProdutoSelecionado));
        edCodigo.setText(Integer.toString(codigoProdutoSelecionado));
    }//GEN-LAST:event_btnSelecionarProdutoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        proximoCodigoChamada = 1;
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void edDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edDescricaoActionPerformed

    private void edNumeroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNumeroItemActionPerformed
       //
    }//GEN-LAST:event_edNumeroItemActionPerformed
    
    private void btnAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutoActionPerformed
        ItemVenda itemVenda2 = new ItemVenda();
        itemVenda2.setNumeroItem(Integer.parseInt(edNumeroItem.getText()));
        itemVenda2.setCodigoProduto(Integer.parseInt(edCodigo.getText()));
        itemVenda2.setQuantidadeVendida(Integer.parseInt(edQuantidade.getText()));
        itemVenda2.setPrecoUnitario(Double.parseDouble(edPreco.getText()));
        itemVenda2.setTotalItem(itemValorTotal);
        itemVenda2.setDescricaoProduto(edDescricao.getText());

        
        if (modeloRegistroVenda != null) {
        modeloRegistroVenda.incluirItemVenda(itemVenda2);
        }
        proximoCodigoChamada++;
        edNumeroItem.setText(Integer.toString(proximoCodigoChamada));
        
        
        if (operacaoCadastroVenda != OperacaoCadastro.consultar) {
            itemValorTotal = Double.parseDouble(edPreco.getText()) * Double.parseDouble(edQuantidade.getText());

            itemVenda2.setTotalItem(itemValorTotal);
            totalVenda += itemValorTotal;
            edTotalVenda.setText("R$ " + Double.toString(totalVenda));
            
            confirmado = true;
            edCodigo.setText(Integer.toString(0));
            edDescricao.setText("");
            edPreco.setText(Double.toString(0));
            edQuantidade.setText(Integer.toString(0));
        }
        
    }//GEN-LAST:event_btnAddProdutoActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        if (operacaoCadastroVenda!= OperacaoCadastro.consultar) {
            itemVenda.setCodigoProduto(Integer.parseInt(edCodigo.getText()));
            itemVenda.setNumeroItem(Integer.parseInt(edNumeroItem.getText()));
            itemVenda.setQuantidadeVendida(Integer.parseInt(edQuantidade.getText()));
            itemVenda.setTotalItem(itemValorTotal);
            itemVenda.setPrecoUnitario(Double.parseDouble(edPreco.getText()));
            itemVenda.setDescricaoProduto(edDescricao.getText());
            venda.setValorTotal(totalVenda);
            venda.setData(dataFormatada);
            venda.setHora(horaFormatada);
            confirmado = true;
            
        }
        totalVenda = 0;
        proximoCodigoChamada = 1;
        dispose();         
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void edPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edPrecoActionPerformed

    private void edTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edTotalVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edTotalVendaActionPerformed

    private void edCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edCodigoFocusGained
        edCodigo.selectAll();
    }//GEN-LAST:event_edCodigoFocusGained

    private void edDescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edDescricaoFocusGained
        edDescricao.selectAll();
    }//GEN-LAST:event_edDescricaoFocusGained

    private void edPrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edPrecoFocusGained
        edPreco.selectAll();
    }//GEN-LAST:event_edPrecoFocusGained

    private void edQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edQuantidadeFocusGained
        edQuantidade.selectAll();
    }//GEN-LAST:event_edQuantidadeFocusGained

    private void edDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edDataActionPerformed

    private void cbPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPagamentoActionPerformed
    
    
    
    public static boolean executar(OperacaoCadastro operecaoCadastroVenda, Venda venda) {
        JanelaRegistroVendaDlg janelaRegistroVendaDlg = new JanelaRegistroVendaDlg(null, operecaoCadastroVenda, venda);
        janelaRegistroVendaDlg.setTitle("Registro de Vendas");
        janelaRegistroVendaDlg.setResizable(false);
        janelaRegistroVendaDlg.setLocationRelativeTo(null);
        janelaRegistroVendaDlg.setVisible(true);
        return janelaRegistroVendaDlg.operacaoConfirmada();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaRegistroVendaDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaRegistroVendaDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaRegistroVendaDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaRegistroVendaDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaRegistroVendaDlg dialog = new JanelaRegistroVendaDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSelecionarProduto;
    private javax.swing.JComboBox<String> cbPagamento;
    private javax.swing.JTextField edCodigo;
    private javax.swing.JTextField edData;
    private javax.swing.JTextField edDescricao;
    private javax.swing.JTextField edHora;
    private javax.swing.JTextField edNumeroItem;
    private javax.swing.JTextField edPreco;
    private javax.swing.JTextField edQuantidade;
    private javax.swing.JTextField edTotalVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabRegistroVenda;
    // End of variables declaration//GEN-END:variables
}
